### ISSUE TITLE
Figure out how to better work with GitHub

### ISSUE THREAD

**Issue by davidyeungcoding** [Americone-Dream/Loiter#16]
Look into how to better work with multiple branches and how to push/pull correctly

**Comment by yeungpirate** [comment]
Review Bootcamp repository 00.1-supplemental -> 04-Week -> Git_Supplemental -> Group_Work.md

**Comment by nmclear** [comment]
Any luck learning GitHub tips? The project and issues have been working great. I need to focus on how to merge and pull correctly.

**Comment by 2juicy** [comment]
After talking to some of my software dev friends, it turns out pulling anything from github is a combination of 'fetching and merging' in 1 command. So no matter what, your changes will get merged with your own work. My friends advice was mostly working on completely different documents to avoid as much conflicts as possible however that is of course not always possible. This means I'm definitely thinking we should do the multiple page setup and having multiple documents for us to work on.
